# Generated by Django 2.1.5 on 2019-03-31 16:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SampleCounter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('text', models.CharField(default='NaN', max_length=100)),
                ('id_number', models.CharField(default='NaN', max_length=18)),
            ],
        ),
        migrations.AddField(
            model_name='postentry',
            name='caption',
            field=models.CharField(default='NaN', max_length=2500),
        ),
        migrations.AddField(
            model_name='postentry',
            name='comments_count',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='postentry',
            name='engagement',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='postentry',
            name='impressions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='postentry',
            name='like_count',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='postentry',
            name='media_object_id',
            field=models.CharField(default='0', max_length=18),
        ),
        migrations.AddField(
            model_name='postentry',
            name='media_type',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='postentry',
            name='media_url',
            field=models.CharField(default='NaN', max_length=250),
        ),
        migrations.AddField(
            model_name='postentry',
            name='permalink',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='postentry',
            name='reach',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='postentry',
            name='saved',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='postentry',
            name='thumbnail_url',
            field=models.CharField(default='NaN', max_length=250),
        ),
        migrations.AddField(
            model_name='postentry',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='postentry',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SampleCounter.Blogger'),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='active_since',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='nickname',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='comments',
            name='related_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SampleCounter.PostEntry'),
        ),
    ]
